version: '3.8'
services:
  nginx-load-balancer:
    image: nginx
    container_name: nginx-load-balancer
    volumes:
      - /opt/load_balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
